### ISSUE TITLE
Build fails after inclusion of `version.h`

### ISSUE THREAD

**Issue by hpretl** [pulp-platform/svase#19]
See https://github.com/pulp-platform/svase/commit/50cb9b9d0acc06f05bb4fe30774f276c188ed942#commitcomment-144541199

**Comment by phsauter** [comment]
Can you try to manually call the script to generate `version.h`:
```
scripts/gen_version.sh > include/version.h
```

**Comment by hpretl** [comment]
It worked with this new line, thanks! I guess you should update the build instructions in the README as well.
